export const FETCH_LAYER_TREE = "FETCH_LAYER_TREE";
export const FETCH_LAYER_DATA = "FETCH_LAYER_DATA";
export const CLEAR_LAYER_DATA = "CLEAR_LAYER_DATA";
export const UPDATE_LAYER_DATA = "UPDATE_LAYER_DATA";
export const STORE_GEOM_COOR = "STORE_GEOM_COOR";
export const STORE_GEOM_DATA = "STORE_GEOM_DATA";
export const CHANGE_MAP_CENTER = "CHANGE_MAP_CENTER";
export const STORE_SHAPE_REF = "STORE_SHAPE_REF";