export const FETCH_LAYER_TREE = "FETCH_LAYER_TREE";
export const FETCH_LAYER_DATA = "FETCH_LAYER_DATA";
export const CLEAR_LAYER_DATA = "CLEAR_LAYER_DATA";
export const UPDATE_LAYER_DATA = "UPDATE_LAYER_DATA";
export const ADD_LAYER_DATA = "ADD_LAYER_DATA";
export const UPDATE_FROM_UNSAVE = "UPDATE_FROM_UNSAVE";

export const STORE_GEOM_COOR = "STORE_GEOM_COOR";
export const STORE_GEOM_DATA = "STORE_GEOM_DATA";
export const RESET_GEOM_DATA = "RESET_GEOM_DATA";
export const CHANGE_MAP_CENTER = "CHANGE_MAP_CENTER";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const SET_CURRENT_EDIT_LAYER = "SET_CURRENT_EDIT_LAYER";
export const SET_BACKUP_GEOM = "SET_BACKUP_GEOM";
export const REVERSE_BACKUP_GEOM = "REVERSE_BACKUP_GEOM";

// user
export const SET_USER = "SET_USER";
export const STORE_SHAPE_REF = "STORE_SHAPE_REF";
export const CLEAR_SHAPE_REF = "CLEAR_SHAPE_REF";

// unsave geom action
export const ADD_TO_UNSAVE = "ADD_TO_UNSAVE";
export const REMOVE_FROM_UNSAVE = "REMOVE_FROM_UNSAVE";
export const TOGGLE_UNSAVE = "TOGGLE_UNSAVE";
export const UPDATE_UNSAVE_LAYER_DATA = "UPDATE_UNSAVE_LAYER_DATA";
export const CLEAR_UNSAVE = "CLEAR_UNSAVE";
export const SET_UNSAVE = "SET_UNSAVE";

export const SET_FULL_COLOR = "SET_FULL_COLOR";
export const SET_PROPERTIES = "SET_PROPERTIES";

export const SET_EDIT = "SET_EDIT";
export const SET_NOT_EDIT = "SET_NOT_EDIT";
export const SET_CURRENT_LAYER_COL = "SET_CURRENT_LAYER_COL";
export const SET_CURRENT_LAYER_STYLE = "SET_CURRENT_LAYER_STYLE";
export const DELETE_GEOM = "DELETE_GEOM";

export const UPDATE_SAVED_LAYER_DATA = "UPDATE_SAVED_LAYER_DATA";

export const SET_R_TREE = "SET_R_TREE";
export const SET_GEOM_R_TREE = "SET_GEOM_R_TREE";
export const GET_MOUSE_POSITION = "GET_MOUSE_POSITION";
export const GET_MOUSE_BOUND = "GET_MOUSE_BOUND";

export const SET_MID_POINT = "SET_MID_POINT";
