export const FETCH_LAYER_TREE = "FETCH_LAYER_TREE";
export const FETCH_LAYER_DATA = "FETCH_LAYER_DATA";
export const CLEAR_LAYER_DATA = "CLEAR_LAYER_DATA";
export const UPDATE_LAYER_DATA = "UPDATE_LAYER_DATA";
export const STORE_GEOM_COOR = "STORE_GEOM_COOR";
export const STORE_GEOM_DATA = "STORE_GEOM_DATA";
export const CHANGE_MAP_CENTER = "CHANGE_MAP_CENTER";
export const SET_CURRENT_EDIT_LAYER = "SET_CURRENT_EDIT_LAYER";

// user
export const SET_USER = "SET_USER";
export const STORE_SHAPE_REF = "STORE_SHAPE_REF";

// unsave geom action
export const ADD_TO_UNSAVE = "ADD_TO_UNSAVE";
export const REMOVE_FROM_UNSAVE = "REMOVE_FROM_UNSAVE";
export const TOGGLE_UNSAVE = "TOGGLE_UNSAVE";

export const SET_COLOR = "SET_COLOR";
export const SET_FILL_COLOR = "SET_FILL_COLOR";
export const SET_FILL_OPACITY = "SET_FILL_OPACITY";
export const SET_WEIGHT = "SET_WEIGHT";
export const SET_FULL_COLOR = "SET_FULL_COLOR";

export const SET_EDIT = "SET_EDIT";
export const SET_NOT_EDIT = "SET_NOT_EDIT";
export const SET_CURRENT_LAYER_COL = "SET_CURRENT_LAYER_COL"